// Copyright 2023, OpenTelemetry Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// This file includes work covered by the following copyright and permission notices:
//
// Copyright 2016 Google Inc. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: opentelemetry/proto/profiles/v1development/profiles.proto

package v1development

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"

	v1 "go.opentelemetry.io/collector/pdata/internal/data/protogen/common/v1"
	v11 "go.opentelemetry.io/collector/pdata/internal/data/protogen/resource/v1"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Specifies the method of aggregating metric values, either DELTA (change since last report)
// or CUMULATIVE (total since a fixed start time).
type AggregationTemporality int32

const (
	// UNSPECIFIED is the default AggregationTemporality, it MUST not be used.
	AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED AggregationTemporality = 0
	// * DELTA is an AggregationTemporality for a profiler which reports
	// changes since last report time. Successive metrics contain aggregation of
	// values from continuous and non-overlapping intervals.
	//
	// The values for a DELTA metric are based only on the time interval
	// associated with one measurement cycle. There is no dependency on
	// previous measurements like is the case for CUMULATIVE metrics.
	//
	// For example, consider a system measuring the number of requests that
	// it receives and reports the sum of these requests every second as a
	// DELTA metric:
	//
	// 1. The system starts receiving at time=t_0.
	// 2. A request is received, the system measures 1 request.
	// 3. A request is received, the system measures 1 request.
	// 4. A request is received, the system measures 1 request.
	// 5. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0 to
	// t_0+1 with a value of 3.
	// 6. A request is received, the system measures 1 request.
	// 7. A request is received, the system measures 1 request.
	// 8. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0+1 to
	// t_0+2 with a value of 2.
	AggregationTemporality_AGGREGATION_TEMPORALITY_DELTA AggregationTemporality = 1
	// * CUMULATIVE is an AggregationTemporality for a profiler which
	// reports changes since a fixed start time. This means that current values
	// of a CUMULATIVE metric depend on all previous measurements since the
	// start time. Because of this, the sender is required to retain this state
	// in some form. If this state is lost or invalidated, the CUMULATIVE metric
	// values MUST be reset and a new fixed start time following the last
	// reported measurement time sent MUST be used.
	//
	// For example, consider a system measuring the number of requests that
	// it receives and reports the sum of these requests every second as a
	// CUMULATIVE metric:
	//
	// 1. The system starts receiving at time=t_0.
	// 2. A request is received, the system measures 1 request.
	// 3. A request is received, the system measures 1 request.
	// 4. A request is received, the system measures 1 request.
	// 5. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0 to
	// t_0+1 with a value of 3.
	// 6. A request is received, the system measures 1 request.
	// 7. A request is received, the system measures 1 request.
	// 8. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_0 to
	// t_0+2 with a value of 5.
	// 9. The system experiences a fault and loses state.
	// 10. The system recovers and resumes receiving at time=t_1.
	// 11. A request is received, the system measures 1 request.
	// 12. The 1 second collection cycle ends. A metric is exported for the
	// number of requests received over the interval of time t_1 to
	// t_1+1 with a value of 1.
	//
	// Note: Even though, when reporting changes since last report time, using
	// CUMULATIVE is valid, it is not recommended.
	AggregationTemporality_AGGREGATION_TEMPORALITY_CUMULATIVE AggregationTemporality = 2
)

// Enum value maps for AggregationTemporality.
var (
	AggregationTemporality_name = map[int32]string{
		0: "AGGREGATION_TEMPORALITY_UNSPECIFIED",
		1: "AGGREGATION_TEMPORALITY_DELTA",
		2: "AGGREGATION_TEMPORALITY_CUMULATIVE",
	}
	AggregationTemporality_value = map[string]int32{
		"AGGREGATION_TEMPORALITY_UNSPECIFIED": 0,
		"AGGREGATION_TEMPORALITY_DELTA":       1,
		"AGGREGATION_TEMPORALITY_CUMULATIVE":  2,
	}
)

func (x AggregationTemporality) Enum() *AggregationTemporality {
	p := new(AggregationTemporality)
	*p = x
	return p
}

func (x AggregationTemporality) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AggregationTemporality) Descriptor() protoreflect.EnumDescriptor {
	return file_opentelemetry_proto_profiles_v1development_profiles_proto_enumTypes[0].Descriptor()
}

func (AggregationTemporality) Type() protoreflect.EnumType {
	return &file_opentelemetry_proto_profiles_v1development_profiles_proto_enumTypes[0]
}

func (x AggregationTemporality) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// ProfilesDictionary represents the profiles data shared across the
// entire message being sent.
type ProfilesDictionary struct {
	state                     protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MappingTable   *[]*Mapping            `protobuf:"bytes,1,rep,name=mapping_table,json=mappingTable,proto3"`
	xxx_hidden_LocationTable  *[]*Location           `protobuf:"bytes,2,rep,name=location_table,json=locationTable,proto3"`
	xxx_hidden_FunctionTable  *[]*Function           `protobuf:"bytes,3,rep,name=function_table,json=functionTable,proto3"`
	xxx_hidden_LinkTable      *[]*Link               `protobuf:"bytes,4,rep,name=link_table,json=linkTable,proto3"`
	xxx_hidden_StringTable    []string               `protobuf:"bytes,5,rep,name=string_table,json=stringTable,proto3"`
	xxx_hidden_AttributeTable *[]*v1.KeyValue        `protobuf:"bytes,6,rep,name=attribute_table,json=attributeTable,proto3"`
	xxx_hidden_AttributeUnits *[]*AttributeUnit      `protobuf:"bytes,7,rep,name=attribute_units,json=attributeUnits,proto3"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ProfilesDictionary) Reset() {
	*x = ProfilesDictionary{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesDictionary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesDictionary) ProtoMessage() {}

func (x *ProfilesDictionary) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilesDictionary) GetMappingTable() []*Mapping {
	if x != nil {
		if x.xxx_hidden_MappingTable != nil {
			return *x.xxx_hidden_MappingTable
		}
	}
	return nil
}

func (x *ProfilesDictionary) GetLocationTable() []*Location {
	if x != nil {
		if x.xxx_hidden_LocationTable != nil {
			return *x.xxx_hidden_LocationTable
		}
	}
	return nil
}

func (x *ProfilesDictionary) GetFunctionTable() []*Function {
	if x != nil {
		if x.xxx_hidden_FunctionTable != nil {
			return *x.xxx_hidden_FunctionTable
		}
	}
	return nil
}

func (x *ProfilesDictionary) GetLinkTable() []*Link {
	if x != nil {
		if x.xxx_hidden_LinkTable != nil {
			return *x.xxx_hidden_LinkTable
		}
	}
	return nil
}

func (x *ProfilesDictionary) GetStringTable() []string {
	if x != nil {
		return x.xxx_hidden_StringTable
	}
	return nil
}

func (x *ProfilesDictionary) GetAttributeTable() []*v1.KeyValue {
	if x != nil {
		if x.xxx_hidden_AttributeTable != nil {
			return *x.xxx_hidden_AttributeTable
		}
	}
	return nil
}

func (x *ProfilesDictionary) GetAttributeUnits() []*AttributeUnit {
	if x != nil {
		if x.xxx_hidden_AttributeUnits != nil {
			return *x.xxx_hidden_AttributeUnits
		}
	}
	return nil
}

func (x *ProfilesDictionary) SetMappingTable(v []*Mapping) {
	x.xxx_hidden_MappingTable = &v
}

func (x *ProfilesDictionary) SetLocationTable(v []*Location) {
	x.xxx_hidden_LocationTable = &v
}

func (x *ProfilesDictionary) SetFunctionTable(v []*Function) {
	x.xxx_hidden_FunctionTable = &v
}

func (x *ProfilesDictionary) SetLinkTable(v []*Link) {
	x.xxx_hidden_LinkTable = &v
}

func (x *ProfilesDictionary) SetStringTable(v []string) {
	x.xxx_hidden_StringTable = v
}

func (x *ProfilesDictionary) SetAttributeTable(v []*v1.KeyValue) {
	x.xxx_hidden_AttributeTable = &v
}

func (x *ProfilesDictionary) SetAttributeUnits(v []*AttributeUnit) {
	x.xxx_hidden_AttributeUnits = &v
}

type ProfilesDictionary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Mappings from address ranges to the image/binary/library mapped
	// into that address range referenced by locations via Location.mapping_index.
	MappingTable []*Mapping
	// Locations referenced by samples via Profile.location_indices.
	LocationTable []*Location
	// Functions referenced by locations via Line.function_index.
	FunctionTable []*Function
	// Links referenced by samples via Sample.link_index.
	LinkTable []*Link
	// A common table for strings referenced by various messages.
	// string_table[0] must always be "".
	StringTable []string
	// A common table for attributes referenced by various messages.
	AttributeTable []*v1.KeyValue
	// Represents a mapping between Attribute Keys and Units.
	AttributeUnits []*AttributeUnit
}

func (b0 ProfilesDictionary_builder) Build() *ProfilesDictionary {
	m0 := &ProfilesDictionary{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MappingTable = &b.MappingTable
	x.xxx_hidden_LocationTable = &b.LocationTable
	x.xxx_hidden_FunctionTable = &b.FunctionTable
	x.xxx_hidden_LinkTable = &b.LinkTable
	x.xxx_hidden_StringTable = b.StringTable
	x.xxx_hidden_AttributeTable = &b.AttributeTable
	x.xxx_hidden_AttributeUnits = &b.AttributeUnits
	return m0
}

// ProfilesData represents the profiles data that can be stored in persistent storage,
// OR can be embedded by other protocols that transfer OTLP profiles data but do not
// implement the OTLP protocol.
//
// The main difference between this message and collector protocol is that
// in this message there will not be any "control" or "metadata" specific to
// OTLP protocol.
//
// When new fields are added into this message, the OTLP request MUST be updated
// as well.
type ProfilesData struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_ResourceProfiles *[]*ResourceProfiles   `protobuf:"bytes,1,rep,name=resource_profiles,json=resourceProfiles,proto3"`
	xxx_hidden_Dictionary       *ProfilesDictionary    `protobuf:"bytes,2,opt,name=dictionary,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *ProfilesData) Reset() {
	*x = ProfilesData{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProfilesData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProfilesData) ProtoMessage() {}

func (x *ProfilesData) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ProfilesData) GetResourceProfiles() []*ResourceProfiles {
	if x != nil {
		if x.xxx_hidden_ResourceProfiles != nil {
			return *x.xxx_hidden_ResourceProfiles
		}
	}
	return nil
}

func (x *ProfilesData) GetDictionary() *ProfilesDictionary {
	if x != nil {
		return x.xxx_hidden_Dictionary
	}
	return nil
}

func (x *ProfilesData) SetResourceProfiles(v []*ResourceProfiles) {
	x.xxx_hidden_ResourceProfiles = &v
}

func (x *ProfilesData) SetDictionary(v *ProfilesDictionary) {
	x.xxx_hidden_Dictionary = v
}

func (x *ProfilesData) HasDictionary() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Dictionary != nil
}

func (x *ProfilesData) ClearDictionary() {
	x.xxx_hidden_Dictionary = nil
}

type ProfilesData_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// An array of ResourceProfiles.
	// For data coming from an SDK profiler, this array will typically contain one
	// element. Host-level profilers will usually create one ResourceProfile per
	// container, as well as one additional ResourceProfile grouping all samples
	// from non-containerized processes.
	// Other resource groupings are possible as well and clarified via
	// Resource.attributes and semantic conventions.
	ResourceProfiles []*ResourceProfiles
	// One instance of ProfilesDictionary
	Dictionary *ProfilesDictionary
}

func (b0 ProfilesData_builder) Build() *ProfilesData {
	m0 := &ProfilesData{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ResourceProfiles = &b.ResourceProfiles
	x.xxx_hidden_Dictionary = b.Dictionary
	return m0
}

// A collection of ScopeProfiles from a Resource.
type ResourceProfiles struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Resource      *v11.Resource          `protobuf:"bytes,1,opt,name=resource,proto3"`
	xxx_hidden_ScopeProfiles *[]*ScopeProfiles      `protobuf:"bytes,2,rep,name=scope_profiles,json=scopeProfiles,proto3"`
	xxx_hidden_SchemaUrl     string                 `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ResourceProfiles) Reset() {
	*x = ResourceProfiles{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceProfiles) ProtoMessage() {}

func (x *ResourceProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ResourceProfiles) GetResource() *v11.Resource {
	if x != nil {
		return x.xxx_hidden_Resource
	}
	return nil
}

func (x *ResourceProfiles) GetScopeProfiles() []*ScopeProfiles {
	if x != nil {
		if x.xxx_hidden_ScopeProfiles != nil {
			return *x.xxx_hidden_ScopeProfiles
		}
	}
	return nil
}

func (x *ResourceProfiles) GetSchemaUrl() string {
	if x != nil {
		return x.xxx_hidden_SchemaUrl
	}
	return ""
}

func (x *ResourceProfiles) SetResource(v *v11.Resource) {
	x.xxx_hidden_Resource = v
}

func (x *ResourceProfiles) SetScopeProfiles(v []*ScopeProfiles) {
	x.xxx_hidden_ScopeProfiles = &v
}

func (x *ResourceProfiles) SetSchemaUrl(v string) {
	x.xxx_hidden_SchemaUrl = v
}

func (x *ResourceProfiles) HasResource() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Resource != nil
}

func (x *ResourceProfiles) ClearResource() {
	x.xxx_hidden_Resource = nil
}

type ResourceProfiles_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The resource for the profiles in this message.
	// If this field is not set then no resource info is known.
	Resource *v11.Resource
	// A list of ScopeProfiles that originate from a resource.
	ScopeProfiles []*ScopeProfiles
	// The Schema URL, if known. This is the identifier of the Schema that the resource data
	// is recorded in. Notably, the last part of the URL path is the version number of the
	// schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	// This schema_url applies to the data in the "resource" field. It does not apply
	// to the data in the "scope_profiles" field which have their own schema_url field.
	SchemaUrl string
}

func (b0 ResourceProfiles_builder) Build() *ResourceProfiles {
	m0 := &ResourceProfiles{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Resource = b.Resource
	x.xxx_hidden_ScopeProfiles = &b.ScopeProfiles
	x.xxx_hidden_SchemaUrl = b.SchemaUrl
	return m0
}

// A collection of Profiles produced by an InstrumentationScope.
type ScopeProfiles struct {
	state                protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Scope     *v1.InstrumentationScope `protobuf:"bytes,1,opt,name=scope,proto3"`
	xxx_hidden_Profiles  *[]*Profile              `protobuf:"bytes,2,rep,name=profiles,proto3"`
	xxx_hidden_SchemaUrl string                   `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *ScopeProfiles) Reset() {
	*x = ScopeProfiles{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScopeProfiles) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScopeProfiles) ProtoMessage() {}

func (x *ScopeProfiles) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScopeProfiles) GetScope() *v1.InstrumentationScope {
	if x != nil {
		return x.xxx_hidden_Scope
	}
	return nil
}

func (x *ScopeProfiles) GetProfiles() []*Profile {
	if x != nil {
		if x.xxx_hidden_Profiles != nil {
			return *x.xxx_hidden_Profiles
		}
	}
	return nil
}

func (x *ScopeProfiles) GetSchemaUrl() string {
	if x != nil {
		return x.xxx_hidden_SchemaUrl
	}
	return ""
}

func (x *ScopeProfiles) SetScope(v *v1.InstrumentationScope) {
	x.xxx_hidden_Scope = v
}

func (x *ScopeProfiles) SetProfiles(v []*Profile) {
	x.xxx_hidden_Profiles = &v
}

func (x *ScopeProfiles) SetSchemaUrl(v string) {
	x.xxx_hidden_SchemaUrl = v
}

func (x *ScopeProfiles) HasScope() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Scope != nil
}

func (x *ScopeProfiles) ClearScope() {
	x.xxx_hidden_Scope = nil
}

type ScopeProfiles_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The instrumentation scope information for the profiles in this message.
	// Semantically when InstrumentationScope isn't set, it is equivalent with
	// an empty instrumentation scope name (unknown).
	Scope *v1.InstrumentationScope
	// A list of Profiles that originate from an instrumentation scope.
	Profiles []*Profile
	// The Schema URL, if known. This is the identifier of the Schema that the profile data
	// is recorded in. Notably, the last part of the URL path is the version number of the
	// schema: http[s]://server[:port]/path/<version>. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	// This schema_url applies to all profiles in the "profiles" field.
	SchemaUrl string
}

func (b0 ScopeProfiles_builder) Build() *ScopeProfiles {
	m0 := &ScopeProfiles{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Scope = b.Scope
	x.xxx_hidden_Profiles = &b.Profiles
	x.xxx_hidden_SchemaUrl = b.SchemaUrl
	return m0
}

// Represents a complete profile, including sample types, samples,
// mappings to binaries, locations, functions, string table, and additional metadata.
// It modifies and annotates pprof Profile with OpenTelemetry specific fields.
//
// Note that whilst fields in this message retain the name and field id from pprof in most cases
// for ease of understanding data migration, it is not intended that pprof:Profile and
// OpenTelemetry:Profile encoding be wire compatible.
type Profile struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_SampleType             *[]*ValueType          `protobuf:"bytes,1,rep,name=sample_type,json=sampleType,proto3"`
	xxx_hidden_Sample                 *[]*Sample             `protobuf:"bytes,2,rep,name=sample,proto3"`
	xxx_hidden_LocationIndices        []int32                `protobuf:"varint,3,rep,packed,name=location_indices,json=locationIndices,proto3"`
	xxx_hidden_TimeNanos              int64                  `protobuf:"varint,4,opt,name=time_nanos,json=timeNanos,proto3"`
	xxx_hidden_DurationNanos          int64                  `protobuf:"varint,5,opt,name=duration_nanos,json=durationNanos,proto3"`
	xxx_hidden_PeriodType             *ValueType             `protobuf:"bytes,6,opt,name=period_type,json=periodType,proto3"`
	xxx_hidden_Period                 int64                  `protobuf:"varint,7,opt,name=period,proto3"`
	xxx_hidden_CommentStrindices      []int32                `protobuf:"varint,8,rep,packed,name=comment_strindices,json=commentStrindices,proto3"`
	xxx_hidden_DefaultSampleTypeIndex int32                  `protobuf:"varint,9,opt,name=default_sample_type_index,json=defaultSampleTypeIndex,proto3"`
	xxx_hidden_ProfileId              []byte                 `protobuf:"bytes,10,opt,name=profile_id,json=profileId,proto3"`
	xxx_hidden_DroppedAttributesCount uint32                 `protobuf:"varint,11,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3"`
	xxx_hidden_OriginalPayloadFormat  string                 `protobuf:"bytes,12,opt,name=original_payload_format,json=originalPayloadFormat,proto3"`
	xxx_hidden_OriginalPayload        []byte                 `protobuf:"bytes,13,opt,name=original_payload,json=originalPayload,proto3"`
	xxx_hidden_AttributeIndices       []int32                `protobuf:"varint,14,rep,packed,name=attribute_indices,json=attributeIndices,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Profile) GetSampleType() []*ValueType {
	if x != nil {
		if x.xxx_hidden_SampleType != nil {
			return *x.xxx_hidden_SampleType
		}
	}
	return nil
}

func (x *Profile) GetSample() []*Sample {
	if x != nil {
		if x.xxx_hidden_Sample != nil {
			return *x.xxx_hidden_Sample
		}
	}
	return nil
}

func (x *Profile) GetLocationIndices() []int32 {
	if x != nil {
		return x.xxx_hidden_LocationIndices
	}
	return nil
}

func (x *Profile) GetTimeNanos() int64 {
	if x != nil {
		return x.xxx_hidden_TimeNanos
	}
	return 0
}

func (x *Profile) GetDurationNanos() int64 {
	if x != nil {
		return x.xxx_hidden_DurationNanos
	}
	return 0
}

func (x *Profile) GetPeriodType() *ValueType {
	if x != nil {
		return x.xxx_hidden_PeriodType
	}
	return nil
}

func (x *Profile) GetPeriod() int64 {
	if x != nil {
		return x.xxx_hidden_Period
	}
	return 0
}

func (x *Profile) GetCommentStrindices() []int32 {
	if x != nil {
		return x.xxx_hidden_CommentStrindices
	}
	return nil
}

func (x *Profile) GetDefaultSampleTypeIndex() int32 {
	if x != nil {
		return x.xxx_hidden_DefaultSampleTypeIndex
	}
	return 0
}

func (x *Profile) GetProfileId() []byte {
	if x != nil {
		return x.xxx_hidden_ProfileId
	}
	return nil
}

func (x *Profile) GetDroppedAttributesCount() uint32 {
	if x != nil {
		return x.xxx_hidden_DroppedAttributesCount
	}
	return 0
}

func (x *Profile) GetOriginalPayloadFormat() string {
	if x != nil {
		return x.xxx_hidden_OriginalPayloadFormat
	}
	return ""
}

func (x *Profile) GetOriginalPayload() []byte {
	if x != nil {
		return x.xxx_hidden_OriginalPayload
	}
	return nil
}

func (x *Profile) GetAttributeIndices() []int32 {
	if x != nil {
		return x.xxx_hidden_AttributeIndices
	}
	return nil
}

func (x *Profile) SetSampleType(v []*ValueType) {
	x.xxx_hidden_SampleType = &v
}

func (x *Profile) SetSample(v []*Sample) {
	x.xxx_hidden_Sample = &v
}

func (x *Profile) SetLocationIndices(v []int32) {
	x.xxx_hidden_LocationIndices = v
}

func (x *Profile) SetTimeNanos(v int64) {
	x.xxx_hidden_TimeNanos = v
}

func (x *Profile) SetDurationNanos(v int64) {
	x.xxx_hidden_DurationNanos = v
}

func (x *Profile) SetPeriodType(v *ValueType) {
	x.xxx_hidden_PeriodType = v
}

func (x *Profile) SetPeriod(v int64) {
	x.xxx_hidden_Period = v
}

func (x *Profile) SetCommentStrindices(v []int32) {
	x.xxx_hidden_CommentStrindices = v
}

func (x *Profile) SetDefaultSampleTypeIndex(v int32) {
	x.xxx_hidden_DefaultSampleTypeIndex = v
}

func (x *Profile) SetProfileId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_ProfileId = v
}

func (x *Profile) SetDroppedAttributesCount(v uint32) {
	x.xxx_hidden_DroppedAttributesCount = v
}

func (x *Profile) SetOriginalPayloadFormat(v string) {
	x.xxx_hidden_OriginalPayloadFormat = v
}

func (x *Profile) SetOriginalPayload(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_OriginalPayload = v
}

func (x *Profile) SetAttributeIndices(v []int32) {
	x.xxx_hidden_AttributeIndices = v
}

func (x *Profile) HasPeriodType() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PeriodType != nil
}

func (x *Profile) ClearPeriodType() {
	x.xxx_hidden_PeriodType = nil
}

type Profile_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A description of the samples associated with each Sample.value.
	// For a cpu profile this might be:
	//
	//	[["cpu","nanoseconds"]] or [["wall","seconds"]] or [["syscall","count"]]
	//
	// For a heap profile, this might be:
	//
	//	[["allocations","count"], ["space","bytes"]],
	//
	// If one of the values represents the number of events represented
	// by the sample, by convention it should be at index 0 and use
	// sample_type.unit == "count".
	SampleType []*ValueType
	// The set of samples recorded in this profile.
	Sample []*Sample
	// References to locations in ProfilesDictionary.location_table.
	LocationIndices []int32
	// Time of collection (UTC) represented as nanoseconds past the epoch.
	TimeNanos int64
	// Duration of the profile, if a duration makes sense.
	DurationNanos int64
	// The kind of events between sampled occurrences.
	// e.g [ "cpu","cycles" ] or [ "heap","bytes" ]
	PeriodType *ValueType
	// The number of events between sampled occurrences.
	Period int64
	// Free-form text associated with the profile. The text is displayed as is
	// to the user by the tools that read profiles (e.g. by pprof). This field
	// should not be used to store any machine-readable information, it is only
	// for human-friendly content. The profile must stay functional if this field
	// is cleaned.
	CommentStrindices []int32
	// Index into the sample_type array to the default sample type.
	DefaultSampleTypeIndex int32
	// A globally unique identifier for a profile. The ID is a 16-byte array. An ID with
	// all zeroes is considered invalid.
	//
	// This field is required.
	ProfileId []byte
	// dropped_attributes_count is the number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32
	// Specifies format of the original payload. Common values are defined in semantic conventions. [required if original_payload is present]
	OriginalPayloadFormat string
	// Original payload can be stored in this field. This can be useful for users who want to get the original payload.
	// Formats such as JFR are highly extensible and can contain more information than what is defined in this spec.
	// Inclusion of original payload should be configurable by the user. Default behavior should be to not include the original payload.
	// If the original payload is in pprof format, it SHOULD not be included in this field.
	// The field is optional, however if it is present then equivalent converted data should be populated in other fields
	// of this message as far as is practicable.
	OriginalPayload []byte
	// References to attributes in attribute_table. [optional]
	// It is a collection of key/value pairs. Note, global attributes
	// like server name can be set using the resource API. Examples of attributes:
	//
	//	"/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
	//	"/http/server_latency": 300
	//	"abc.com/myattribute": true
	//	"abc.com/score": 10.239
	//
	// The OpenTelemetry API specification further restricts the allowed value types:
	// https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	AttributeIndices []int32
}

func (b0 Profile_builder) Build() *Profile {
	m0 := &Profile{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SampleType = &b.SampleType
	x.xxx_hidden_Sample = &b.Sample
	x.xxx_hidden_LocationIndices = b.LocationIndices
	x.xxx_hidden_TimeNanos = b.TimeNanos
	x.xxx_hidden_DurationNanos = b.DurationNanos
	x.xxx_hidden_PeriodType = b.PeriodType
	x.xxx_hidden_Period = b.Period
	x.xxx_hidden_CommentStrindices = b.CommentStrindices
	x.xxx_hidden_DefaultSampleTypeIndex = b.DefaultSampleTypeIndex
	x.xxx_hidden_ProfileId = b.ProfileId
	x.xxx_hidden_DroppedAttributesCount = b.DroppedAttributesCount
	x.xxx_hidden_OriginalPayloadFormat = b.OriginalPayloadFormat
	x.xxx_hidden_OriginalPayload = b.OriginalPayload
	x.xxx_hidden_AttributeIndices = b.AttributeIndices
	return m0
}

// Represents a mapping between Attribute Keys and Units.
type AttributeUnit struct {
	state                           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AttributeKeyStrindex int32                  `protobuf:"varint,1,opt,name=attribute_key_strindex,json=attributeKeyStrindex,proto3"`
	xxx_hidden_UnitStrindex         int32                  `protobuf:"varint,2,opt,name=unit_strindex,json=unitStrindex,proto3"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *AttributeUnit) Reset() {
	*x = AttributeUnit{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeUnit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeUnit) ProtoMessage() {}

func (x *AttributeUnit) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *AttributeUnit) GetAttributeKeyStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_AttributeKeyStrindex
	}
	return 0
}

func (x *AttributeUnit) GetUnitStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_UnitStrindex
	}
	return 0
}

func (x *AttributeUnit) SetAttributeKeyStrindex(v int32) {
	x.xxx_hidden_AttributeKeyStrindex = v
}

func (x *AttributeUnit) SetUnitStrindex(v int32) {
	x.xxx_hidden_UnitStrindex = v
}

type AttributeUnit_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Index into string table.
	AttributeKeyStrindex int32
	// Index into string table.
	UnitStrindex int32
}

func (b0 AttributeUnit_builder) Build() *AttributeUnit {
	m0 := &AttributeUnit{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AttributeKeyStrindex = b.AttributeKeyStrindex
	x.xxx_hidden_UnitStrindex = b.UnitStrindex
	return m0
}

// A pointer from a profile Sample to a trace Span.
// Connects a profile sample to a trace span, identified by unique trace and span IDs.
type Link struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TraceId []byte                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3"`
	xxx_hidden_SpanId  []byte                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Link) GetTraceId() []byte {
	if x != nil {
		return x.xxx_hidden_TraceId
	}
	return nil
}

func (x *Link) GetSpanId() []byte {
	if x != nil {
		return x.xxx_hidden_SpanId
	}
	return nil
}

func (x *Link) SetTraceId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_TraceId = v
}

func (x *Link) SetSpanId(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_SpanId = v
}

type Link_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// A unique identifier of a trace that this linked span is part of. The ID is a
	// 16-byte array.
	TraceId []byte
	// A unique identifier for the linked span. The ID is an 8-byte array.
	SpanId []byte
}

func (b0 Link_builder) Build() *Link {
	m0 := &Link{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TraceId = b.TraceId
	x.xxx_hidden_SpanId = b.SpanId
	return m0
}

// ValueType describes the type and units of a value, with an optional aggregation temporality.
type ValueType struct {
	state                             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TypeStrindex           int32                  `protobuf:"varint,1,opt,name=type_strindex,json=typeStrindex,proto3"`
	xxx_hidden_UnitStrindex           int32                  `protobuf:"varint,2,opt,name=unit_strindex,json=unitStrindex,proto3"`
	xxx_hidden_AggregationTemporality AggregationTemporality `protobuf:"varint,3,opt,name=aggregation_temporality,json=aggregationTemporality,proto3,enum=opentelemetry.proto.profiles.v1development.AggregationTemporality"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *ValueType) Reset() {
	*x = ValueType{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValueType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueType) ProtoMessage() {}

func (x *ValueType) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ValueType) GetTypeStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_TypeStrindex
	}
	return 0
}

func (x *ValueType) GetUnitStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_UnitStrindex
	}
	return 0
}

func (x *ValueType) GetAggregationTemporality() AggregationTemporality {
	if x != nil {
		return x.xxx_hidden_AggregationTemporality
	}
	return AggregationTemporality_AGGREGATION_TEMPORALITY_UNSPECIFIED
}

func (x *ValueType) SetTypeStrindex(v int32) {
	x.xxx_hidden_TypeStrindex = v
}

func (x *ValueType) SetUnitStrindex(v int32) {
	x.xxx_hidden_UnitStrindex = v
}

func (x *ValueType) SetAggregationTemporality(v AggregationTemporality) {
	x.xxx_hidden_AggregationTemporality = v
}

type ValueType_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TypeStrindex           int32
	UnitStrindex           int32
	AggregationTemporality AggregationTemporality
}

func (b0 ValueType_builder) Build() *ValueType {
	m0 := &ValueType{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TypeStrindex = b.TypeStrindex
	x.xxx_hidden_UnitStrindex = b.UnitStrindex
	x.xxx_hidden_AggregationTemporality = b.AggregationTemporality
	return m0
}

// Each Sample records values encountered in some program
// context. The program context is typically a stack trace, perhaps
// augmented with auxiliary information like the thread-id, some
// indicator of a higher level request being handled etc.
type Sample struct {
	state                          protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_LocationsStartIndex int32                  `protobuf:"varint,1,opt,name=locations_start_index,json=locationsStartIndex,proto3"`
	xxx_hidden_LocationsLength     int32                  `protobuf:"varint,2,opt,name=locations_length,json=locationsLength,proto3"`
	xxx_hidden_Value               []int64                `protobuf:"varint,3,rep,packed,name=value,proto3"`
	xxx_hidden_AttributeIndices    []int32                `protobuf:"varint,4,rep,packed,name=attribute_indices,json=attributeIndices,proto3"`
	xxx_hidden_LinkIndex           int32                  `protobuf:"varint,5,opt,name=link_index,json=linkIndex,proto3,oneof"`
	xxx_hidden_TimestampsUnixNano  []uint64               `protobuf:"varint,6,rep,packed,name=timestamps_unix_nano,json=timestampsUnixNano,proto3"`
	XXX_raceDetectHookData         protoimpl.RaceDetectHookData
	XXX_presence                   [1]uint32
	unknownFields                  protoimpl.UnknownFields
	sizeCache                      protoimpl.SizeCache
}

func (x *Sample) Reset() {
	*x = Sample{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Sample) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sample) ProtoMessage() {}

func (x *Sample) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Sample) GetLocationsStartIndex() int32 {
	if x != nil {
		return x.xxx_hidden_LocationsStartIndex
	}
	return 0
}

func (x *Sample) GetLocationsLength() int32 {
	if x != nil {
		return x.xxx_hidden_LocationsLength
	}
	return 0
}

func (x *Sample) GetValue() []int64 {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *Sample) GetAttributeIndices() []int32 {
	if x != nil {
		return x.xxx_hidden_AttributeIndices
	}
	return nil
}

func (x *Sample) GetLinkIndex() int32 {
	if x != nil {
		return x.xxx_hidden_LinkIndex
	}
	return 0
}

func (x *Sample) GetTimestampsUnixNano() []uint64 {
	if x != nil {
		return x.xxx_hidden_TimestampsUnixNano
	}
	return nil
}

func (x *Sample) SetLocationsStartIndex(v int32) {
	x.xxx_hidden_LocationsStartIndex = v
}

func (x *Sample) SetLocationsLength(v int32) {
	x.xxx_hidden_LocationsLength = v
}

func (x *Sample) SetValue(v []int64) {
	x.xxx_hidden_Value = v
}

func (x *Sample) SetAttributeIndices(v []int32) {
	x.xxx_hidden_AttributeIndices = v
}

func (x *Sample) SetLinkIndex(v int32) {
	x.xxx_hidden_LinkIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 6)
}

func (x *Sample) SetTimestampsUnixNano(v []uint64) {
	x.xxx_hidden_TimestampsUnixNano = v
}

func (x *Sample) HasLinkIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Sample) ClearLinkIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_LinkIndex = 0
}

type Sample_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// locations_start_index along with locations_length refers to to a slice of locations in Profile.location_indices.
	LocationsStartIndex int32
	// locations_length along with locations_start_index refers to a slice of locations in Profile.location_indices.
	// Supersedes location_index.
	LocationsLength int32
	// The type and unit of each value is defined by the corresponding
	// entry in Profile.sample_type. All samples must have the same
	// number of values, the same as the length of Profile.sample_type.
	// When aggregating multiple samples into a single sample, the
	// result has a list of values that is the element-wise sum of the
	// lists of the originals.
	Value []int64
	// References to attributes in ProfilesDictionary.attribute_table. [optional]
	AttributeIndices []int32
	// Reference to link in ProfilesDictionary.link_table. [optional]
	LinkIndex *int32
	// Timestamps associated with Sample represented in nanoseconds. These timestamps are expected
	// to fall within the Profile's time range. [optional]
	TimestampsUnixNano []uint64
}

func (b0 Sample_builder) Build() *Sample {
	m0 := &Sample{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_LocationsStartIndex = b.LocationsStartIndex
	x.xxx_hidden_LocationsLength = b.LocationsLength
	x.xxx_hidden_Value = b.Value
	x.xxx_hidden_AttributeIndices = b.AttributeIndices
	if b.LinkIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 6)
		x.xxx_hidden_LinkIndex = *b.LinkIndex
	}
	x.xxx_hidden_TimestampsUnixNano = b.TimestampsUnixNano
	return m0
}

// Describes the mapping of a binary in memory, including its address range,
// file offset, and metadata like build ID
type Mapping struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MemoryStart      uint64                 `protobuf:"varint,1,opt,name=memory_start,json=memoryStart,proto3"`
	xxx_hidden_MemoryLimit      uint64                 `protobuf:"varint,2,opt,name=memory_limit,json=memoryLimit,proto3"`
	xxx_hidden_FileOffset       uint64                 `protobuf:"varint,3,opt,name=file_offset,json=fileOffset,proto3"`
	xxx_hidden_FilenameStrindex int32                  `protobuf:"varint,4,opt,name=filename_strindex,json=filenameStrindex,proto3"`
	xxx_hidden_AttributeIndices []int32                `protobuf:"varint,5,rep,packed,name=attribute_indices,json=attributeIndices,proto3"`
	xxx_hidden_HasFunctions     bool                   `protobuf:"varint,6,opt,name=has_functions,json=hasFunctions,proto3"`
	xxx_hidden_HasFilenames     bool                   `protobuf:"varint,7,opt,name=has_filenames,json=hasFilenames,proto3"`
	xxx_hidden_HasLineNumbers   bool                   `protobuf:"varint,8,opt,name=has_line_numbers,json=hasLineNumbers,proto3"`
	xxx_hidden_HasInlineFrames  bool                   `protobuf:"varint,9,opt,name=has_inline_frames,json=hasInlineFrames,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Mapping) Reset() {
	*x = Mapping{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Mapping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Mapping) ProtoMessage() {}

func (x *Mapping) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Mapping) GetMemoryStart() uint64 {
	if x != nil {
		return x.xxx_hidden_MemoryStart
	}
	return 0
}

func (x *Mapping) GetMemoryLimit() uint64 {
	if x != nil {
		return x.xxx_hidden_MemoryLimit
	}
	return 0
}

func (x *Mapping) GetFileOffset() uint64 {
	if x != nil {
		return x.xxx_hidden_FileOffset
	}
	return 0
}

func (x *Mapping) GetFilenameStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_FilenameStrindex
	}
	return 0
}

func (x *Mapping) GetAttributeIndices() []int32 {
	if x != nil {
		return x.xxx_hidden_AttributeIndices
	}
	return nil
}

func (x *Mapping) GetHasFunctions() bool {
	if x != nil {
		return x.xxx_hidden_HasFunctions
	}
	return false
}

func (x *Mapping) GetHasFilenames() bool {
	if x != nil {
		return x.xxx_hidden_HasFilenames
	}
	return false
}

func (x *Mapping) GetHasLineNumbers() bool {
	if x != nil {
		return x.xxx_hidden_HasLineNumbers
	}
	return false
}

func (x *Mapping) GetHasInlineFrames() bool {
	if x != nil {
		return x.xxx_hidden_HasInlineFrames
	}
	return false
}

func (x *Mapping) SetMemoryStart(v uint64) {
	x.xxx_hidden_MemoryStart = v
}

func (x *Mapping) SetMemoryLimit(v uint64) {
	x.xxx_hidden_MemoryLimit = v
}

func (x *Mapping) SetFileOffset(v uint64) {
	x.xxx_hidden_FileOffset = v
}

func (x *Mapping) SetFilenameStrindex(v int32) {
	x.xxx_hidden_FilenameStrindex = v
}

func (x *Mapping) SetAttributeIndices(v []int32) {
	x.xxx_hidden_AttributeIndices = v
}

func (x *Mapping) SetHasFunctions(v bool) {
	x.xxx_hidden_HasFunctions = v
}

func (x *Mapping) SetHasFilenames(v bool) {
	x.xxx_hidden_HasFilenames = v
}

func (x *Mapping) SetHasLineNumbers(v bool) {
	x.xxx_hidden_HasLineNumbers = v
}

func (x *Mapping) SetHasInlineFrames(v bool) {
	x.xxx_hidden_HasInlineFrames = v
}

type Mapping_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Address at which the binary (or DLL) is loaded into memory.
	MemoryStart uint64
	// The limit of the address range occupied by this mapping.
	MemoryLimit uint64
	// Offset in the binary that corresponds to the first mapped address.
	FileOffset uint64
	// The object this entry is loaded from.  This can be a filename on
	// disk for the main binary and shared libraries, or virtual
	// abstractions like "[vdso]".
	FilenameStrindex int32
	// References to attributes in ProfilesDictionary.attribute_table. [optional]
	AttributeIndices []int32
	// The following fields indicate the resolution of symbolic info.
	HasFunctions    bool
	HasFilenames    bool
	HasLineNumbers  bool
	HasInlineFrames bool
}

func (b0 Mapping_builder) Build() *Mapping {
	m0 := &Mapping{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MemoryStart = b.MemoryStart
	x.xxx_hidden_MemoryLimit = b.MemoryLimit
	x.xxx_hidden_FileOffset = b.FileOffset
	x.xxx_hidden_FilenameStrindex = b.FilenameStrindex
	x.xxx_hidden_AttributeIndices = b.AttributeIndices
	x.xxx_hidden_HasFunctions = b.HasFunctions
	x.xxx_hidden_HasFilenames = b.HasFilenames
	x.xxx_hidden_HasLineNumbers = b.HasLineNumbers
	x.xxx_hidden_HasInlineFrames = b.HasInlineFrames
	return m0
}

// Describes function and line table debug information.
type Location struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_MappingIndex     int32                  `protobuf:"varint,1,opt,name=mapping_index,json=mappingIndex,proto3,oneof"`
	xxx_hidden_Address          uint64                 `protobuf:"varint,2,opt,name=address,proto3"`
	xxx_hidden_Line             *[]*Line               `protobuf:"bytes,3,rep,name=line,proto3"`
	xxx_hidden_IsFolded         bool                   `protobuf:"varint,4,opt,name=is_folded,json=isFolded,proto3"`
	xxx_hidden_AttributeIndices []int32                `protobuf:"varint,5,rep,packed,name=attribute_indices,json=attributeIndices,proto3"`
	XXX_raceDetectHookData      protoimpl.RaceDetectHookData
	XXX_presence                [1]uint32
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Location) GetMappingIndex() int32 {
	if x != nil {
		return x.xxx_hidden_MappingIndex
	}
	return 0
}

func (x *Location) GetAddress() uint64 {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return 0
}

func (x *Location) GetLine() []*Line {
	if x != nil {
		if x.xxx_hidden_Line != nil {
			return *x.xxx_hidden_Line
		}
	}
	return nil
}

func (x *Location) GetIsFolded() bool {
	if x != nil {
		return x.xxx_hidden_IsFolded
	}
	return false
}

func (x *Location) GetAttributeIndices() []int32 {
	if x != nil {
		return x.xxx_hidden_AttributeIndices
	}
	return nil
}

func (x *Location) SetMappingIndex(v int32) {
	x.xxx_hidden_MappingIndex = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Location) SetAddress(v uint64) {
	x.xxx_hidden_Address = v
}

func (x *Location) SetLine(v []*Line) {
	x.xxx_hidden_Line = &v
}

func (x *Location) SetIsFolded(v bool) {
	x.xxx_hidden_IsFolded = v
}

func (x *Location) SetAttributeIndices(v []int32) {
	x.xxx_hidden_AttributeIndices = v
}

func (x *Location) HasMappingIndex() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Location) ClearMappingIndex() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_MappingIndex = 0
}

type Location_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reference to mapping in ProfilesDictionary.mapping_table.
	// It can be unset if the mapping is unknown or not applicable for
	// this profile type.
	MappingIndex *int32
	// The instruction address for this location, if available.  It
	// should be within [Mapping.memory_start...Mapping.memory_limit]
	// for the corresponding mapping. A non-leaf address may be in the
	// middle of a call instruction. It is up to display tools to find
	// the beginning of the instruction if necessary.
	Address uint64
	// Multiple line indicates this location has inlined functions,
	// where the last entry represents the caller into which the
	// preceding entries were inlined.
	//
	// E.g., if memcpy() is inlined into printf:
	//
	//	line[0].function_name == "memcpy"
	//	line[1].function_name == "printf"
	Line []*Line
	// Provides an indication that multiple symbols map to this location's
	// address, for example due to identical code folding by the linker. In that
	// case the line information above represents one of the multiple
	// symbols. This field must be recomputed when the symbolization state of the
	// profile changes.
	IsFolded bool
	// References to attributes in ProfilesDictionary.attribute_table. [optional]
	AttributeIndices []int32
}

func (b0 Location_builder) Build() *Location {
	m0 := &Location{}
	b, x := &b0, m0
	_, _ = b, x
	if b.MappingIndex != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_MappingIndex = *b.MappingIndex
	}
	x.xxx_hidden_Address = b.Address
	x.xxx_hidden_Line = &b.Line
	x.xxx_hidden_IsFolded = b.IsFolded
	x.xxx_hidden_AttributeIndices = b.AttributeIndices
	return m0
}

// Details a specific line in a source code, linked to a function.
type Line struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_FunctionIndex int32                  `protobuf:"varint,1,opt,name=function_index,json=functionIndex,proto3"`
	xxx_hidden_Line          int64                  `protobuf:"varint,2,opt,name=line,proto3"`
	xxx_hidden_Column        int64                  `protobuf:"varint,3,opt,name=column,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Line) Reset() {
	*x = Line{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Line) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Line) ProtoMessage() {}

func (x *Line) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Line) GetFunctionIndex() int32 {
	if x != nil {
		return x.xxx_hidden_FunctionIndex
	}
	return 0
}

func (x *Line) GetLine() int64 {
	if x != nil {
		return x.xxx_hidden_Line
	}
	return 0
}

func (x *Line) GetColumn() int64 {
	if x != nil {
		return x.xxx_hidden_Column
	}
	return 0
}

func (x *Line) SetFunctionIndex(v int32) {
	x.xxx_hidden_FunctionIndex = v
}

func (x *Line) SetLine(v int64) {
	x.xxx_hidden_Line = v
}

func (x *Line) SetColumn(v int64) {
	x.xxx_hidden_Column = v
}

type Line_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Reference to function in ProfilesDictionary.function_table.
	FunctionIndex int32
	// Line number in source code. 0 means unset.
	Line int64
	// Column number in source code. 0 means unset.
	Column int64
}

func (b0 Line_builder) Build() *Line {
	m0 := &Line{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_FunctionIndex = b.FunctionIndex
	x.xxx_hidden_Line = b.Line
	x.xxx_hidden_Column = b.Column
	return m0
}

// Describes a function, including its human-readable name, system name,
// source file, and starting line number in the source.
type Function struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_NameStrindex       int32                  `protobuf:"varint,1,opt,name=name_strindex,json=nameStrindex,proto3"`
	xxx_hidden_SystemNameStrindex int32                  `protobuf:"varint,2,opt,name=system_name_strindex,json=systemNameStrindex,proto3"`
	xxx_hidden_FilenameStrindex   int32                  `protobuf:"varint,3,opt,name=filename_strindex,json=filenameStrindex,proto3"`
	xxx_hidden_StartLine          int64                  `protobuf:"varint,4,opt,name=start_line,json=startLine,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *Function) Reset() {
	*x = Function{}
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Function) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Function) ProtoMessage() {}

func (x *Function) ProtoReflect() protoreflect.Message {
	mi := &file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Function) GetNameStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_NameStrindex
	}
	return 0
}

func (x *Function) GetSystemNameStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_SystemNameStrindex
	}
	return 0
}

func (x *Function) GetFilenameStrindex() int32 {
	if x != nil {
		return x.xxx_hidden_FilenameStrindex
	}
	return 0
}

func (x *Function) GetStartLine() int64 {
	if x != nil {
		return x.xxx_hidden_StartLine
	}
	return 0
}

func (x *Function) SetNameStrindex(v int32) {
	x.xxx_hidden_NameStrindex = v
}

func (x *Function) SetSystemNameStrindex(v int32) {
	x.xxx_hidden_SystemNameStrindex = v
}

func (x *Function) SetFilenameStrindex(v int32) {
	x.xxx_hidden_FilenameStrindex = v
}

func (x *Function) SetStartLine(v int64) {
	x.xxx_hidden_StartLine = v
}

type Function_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Function name. Empty string if not available.
	NameStrindex int32
	// Function name, as identified by the system. For instance,
	// it can be a C++ mangled name. Empty string if not available.
	SystemNameStrindex int32
	// Source file containing the function. Empty string if not available.
	FilenameStrindex int32
	// Line number in source file. 0 means unset.
	StartLine int64
}

func (b0 Function_builder) Build() *Function {
	m0 := &Function{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NameStrindex = b.NameStrindex
	x.xxx_hidden_SystemNameStrindex = b.SystemNameStrindex
	x.xxx_hidden_FilenameStrindex = b.FilenameStrindex
	x.xxx_hidden_StartLine = b.StartLine
	return m0
}

var File_opentelemetry_proto_profiles_v1development_profiles_proto protoreflect.FileDescriptor

const file_opentelemetry_proto_profiles_v1development_profiles_proto_rawDesc = "" +
	"\n" +
	"9opentelemetry/proto/profiles/v1development/profiles.proto\x12*opentelemetry.proto.profiles.v1development\x1a*opentelemetry/proto/common/v1/common.proto\x1a.opentelemetry/proto/resource/v1/resource.proto\"\xd2\x04\n" +
	"\x12ProfilesDictionary\x12X\n" +
	"\rmapping_table\x18\x01 \x03(\v23.opentelemetry.proto.profiles.v1development.MappingR\fmappingTable\x12[\n" +
	"\x0elocation_table\x18\x02 \x03(\v24.opentelemetry.proto.profiles.v1development.LocationR\rlocationTable\x12[\n" +
	"\x0efunction_table\x18\x03 \x03(\v24.opentelemetry.proto.profiles.v1development.FunctionR\rfunctionTable\x12O\n" +
	"\n" +
	"link_table\x18\x04 \x03(\v20.opentelemetry.proto.profiles.v1development.LinkR\tlinkTable\x12!\n" +
	"\fstring_table\x18\x05 \x03(\tR\vstringTable\x12P\n" +
	"\x0fattribute_table\x18\x06 \x03(\v2'.opentelemetry.proto.common.v1.KeyValueR\x0eattributeTable\x12b\n" +
	"\x0fattribute_units\x18\a \x03(\v29.opentelemetry.proto.profiles.v1development.AttributeUnitR\x0eattributeUnits\"\xd9\x01\n" +
	"\fProfilesData\x12i\n" +
	"\x11resource_profiles\x18\x01 \x03(\v2<.opentelemetry.proto.profiles.v1development.ResourceProfilesR\x10resourceProfiles\x12^\n" +
	"\n" +
	"dictionary\x18\x02 \x01(\v2>.opentelemetry.proto.profiles.v1development.ProfilesDictionaryR\n" +
	"dictionary\"\xe2\x01\n" +
	"\x10ResourceProfiles\x12E\n" +
	"\bresource\x18\x01 \x01(\v2).opentelemetry.proto.resource.v1.ResourceR\bresource\x12`\n" +
	"\x0escope_profiles\x18\x02 \x03(\v29.opentelemetry.proto.profiles.v1development.ScopeProfilesR\rscopeProfiles\x12\x1d\n" +
	"\n" +
	"schema_url\x18\x03 \x01(\tR\tschemaUrlJ\x06\b\xe8\a\x10\xe9\a\"\xca\x01\n" +
	"\rScopeProfiles\x12I\n" +
	"\x05scope\x18\x01 \x01(\v23.opentelemetry.proto.common.v1.InstrumentationScopeR\x05scope\x12O\n" +
	"\bprofiles\x18\x02 \x03(\v23.opentelemetry.proto.profiles.v1development.ProfileR\bprofiles\x12\x1d\n" +
	"\n" +
	"schema_url\x18\x03 \x01(\tR\tschemaUrl\"\xe1\x05\n" +
	"\aProfile\x12V\n" +
	"\vsample_type\x18\x01 \x03(\v25.opentelemetry.proto.profiles.v1development.ValueTypeR\n" +
	"sampleType\x12J\n" +
	"\x06sample\x18\x02 \x03(\v22.opentelemetry.proto.profiles.v1development.SampleR\x06sample\x12)\n" +
	"\x10location_indices\x18\x03 \x03(\x05R\x0flocationIndices\x12\x1d\n" +
	"\n" +
	"time_nanos\x18\x04 \x01(\x03R\ttimeNanos\x12%\n" +
	"\x0eduration_nanos\x18\x05 \x01(\x03R\rdurationNanos\x12V\n" +
	"\vperiod_type\x18\x06 \x01(\v25.opentelemetry.proto.profiles.v1development.ValueTypeR\n" +
	"periodType\x12\x16\n" +
	"\x06period\x18\a \x01(\x03R\x06period\x12-\n" +
	"\x12comment_strindices\x18\b \x03(\x05R\x11commentStrindices\x129\n" +
	"\x19default_sample_type_index\x18\t \x01(\x05R\x16defaultSampleTypeIndex\x12\x1d\n" +
	"\n" +
	"profile_id\x18\n" +
	" \x01(\fR\tprofileId\x128\n" +
	"\x18dropped_attributes_count\x18\v \x01(\rR\x16droppedAttributesCount\x126\n" +
	"\x17original_payload_format\x18\f \x01(\tR\x15originalPayloadFormat\x12)\n" +
	"\x10original_payload\x18\r \x01(\fR\x0foriginalPayload\x12+\n" +
	"\x11attribute_indices\x18\x0e \x03(\x05R\x10attributeIndices\"j\n" +
	"\rAttributeUnit\x124\n" +
	"\x16attribute_key_strindex\x18\x01 \x01(\x05R\x14attributeKeyStrindex\x12#\n" +
	"\runit_strindex\x18\x02 \x01(\x05R\funitStrindex\":\n" +
	"\x04Link\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\fR\x06spanId\"\xd2\x01\n" +
	"\tValueType\x12#\n" +
	"\rtype_strindex\x18\x01 \x01(\x05R\ftypeStrindex\x12#\n" +
	"\runit_strindex\x18\x02 \x01(\x05R\funitStrindex\x12{\n" +
	"\x17aggregation_temporality\x18\x03 \x01(\x0e2B.opentelemetry.proto.profiles.v1development.AggregationTemporalityR\x16aggregationTemporality\"\x8f\x02\n" +
	"\x06Sample\x122\n" +
	"\x15locations_start_index\x18\x01 \x01(\x05R\x13locationsStartIndex\x12)\n" +
	"\x10locations_length\x18\x02 \x01(\x05R\x0flocationsLength\x12\x14\n" +
	"\x05value\x18\x03 \x03(\x03R\x05value\x12+\n" +
	"\x11attribute_indices\x18\x04 \x03(\x05R\x10attributeIndices\x12\"\n" +
	"\n" +
	"link_index\x18\x05 \x01(\x05H\x00R\tlinkIndex\x88\x01\x01\x120\n" +
	"\x14timestamps_unix_nano\x18\x06 \x03(\x04R\x12timestampsUnixNanoB\r\n" +
	"\v_link_index\"\xea\x02\n" +
	"\aMapping\x12!\n" +
	"\fmemory_start\x18\x01 \x01(\x04R\vmemoryStart\x12!\n" +
	"\fmemory_limit\x18\x02 \x01(\x04R\vmemoryLimit\x12\x1f\n" +
	"\vfile_offset\x18\x03 \x01(\x04R\n" +
	"fileOffset\x12+\n" +
	"\x11filename_strindex\x18\x04 \x01(\x05R\x10filenameStrindex\x12+\n" +
	"\x11attribute_indices\x18\x05 \x03(\x05R\x10attributeIndices\x12#\n" +
	"\rhas_functions\x18\x06 \x01(\bR\fhasFunctions\x12#\n" +
	"\rhas_filenames\x18\a \x01(\bR\fhasFilenames\x12(\n" +
	"\x10has_line_numbers\x18\b \x01(\bR\x0ehasLineNumbers\x12*\n" +
	"\x11has_inline_frames\x18\t \x01(\bR\x0fhasInlineFrames\"\xf0\x01\n" +
	"\bLocation\x12(\n" +
	"\rmapping_index\x18\x01 \x01(\x05H\x00R\fmappingIndex\x88\x01\x01\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\x04R\aaddress\x12D\n" +
	"\x04line\x18\x03 \x03(\v20.opentelemetry.proto.profiles.v1development.LineR\x04line\x12\x1b\n" +
	"\tis_folded\x18\x04 \x01(\bR\bisFolded\x12+\n" +
	"\x11attribute_indices\x18\x05 \x03(\x05R\x10attributeIndicesB\x10\n" +
	"\x0e_mapping_index\"Y\n" +
	"\x04Line\x12%\n" +
	"\x0efunction_index\x18\x01 \x01(\x05R\rfunctionIndex\x12\x12\n" +
	"\x04line\x18\x02 \x01(\x03R\x04line\x12\x16\n" +
	"\x06column\x18\x03 \x01(\x03R\x06column\"\xad\x01\n" +
	"\bFunction\x12#\n" +
	"\rname_strindex\x18\x01 \x01(\x05R\fnameStrindex\x120\n" +
	"\x14system_name_strindex\x18\x02 \x01(\x05R\x12systemNameStrindex\x12+\n" +
	"\x11filename_strindex\x18\x03 \x01(\x05R\x10filenameStrindex\x12\x1d\n" +
	"\n" +
	"start_line\x18\x04 \x01(\x03R\tstartLine*\x8c\x01\n" +
	"\x16AggregationTemporality\x12'\n" +
	"#AGGREGATION_TEMPORALITY_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dAGGREGATION_TEMPORALITY_DELTA\x10\x01\x12&\n" +
	"\"AGGREGATION_TEMPORALITY_CUMULATIVE\x10\x02B\xc0\x01\n" +
	"-io.opentelemetry.proto.profiles.v1developmentB\rProfilesProtoP\x01ZQgo.opentelemetry.io/collector/pdata/internal/data/protogen/profiles/v1development\xaa\x02*OpenTelemetry.Proto.Profiles.V1Developmentb\x06proto3"

var file_opentelemetry_proto_profiles_v1development_profiles_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_opentelemetry_proto_profiles_v1development_profiles_proto_goTypes = []any{
	(AggregationTemporality)(0),     // 0: opentelemetry.proto.profiles.v1development.AggregationTemporality
	(*ProfilesDictionary)(nil),      // 1: opentelemetry.proto.profiles.v1development.ProfilesDictionary
	(*ProfilesData)(nil),            // 2: opentelemetry.proto.profiles.v1development.ProfilesData
	(*ResourceProfiles)(nil),        // 3: opentelemetry.proto.profiles.v1development.ResourceProfiles
	(*ScopeProfiles)(nil),           // 4: opentelemetry.proto.profiles.v1development.ScopeProfiles
	(*Profile)(nil),                 // 5: opentelemetry.proto.profiles.v1development.Profile
	(*AttributeUnit)(nil),           // 6: opentelemetry.proto.profiles.v1development.AttributeUnit
	(*Link)(nil),                    // 7: opentelemetry.proto.profiles.v1development.Link
	(*ValueType)(nil),               // 8: opentelemetry.proto.profiles.v1development.ValueType
	(*Sample)(nil),                  // 9: opentelemetry.proto.profiles.v1development.Sample
	(*Mapping)(nil),                 // 10: opentelemetry.proto.profiles.v1development.Mapping
	(*Location)(nil),                // 11: opentelemetry.proto.profiles.v1development.Location
	(*Line)(nil),                    // 12: opentelemetry.proto.profiles.v1development.Line
	(*Function)(nil),                // 13: opentelemetry.proto.profiles.v1development.Function
	(*v1.KeyValue)(nil),             // 14: opentelemetry.proto.common.v1.KeyValue
	(*v11.Resource)(nil),            // 15: opentelemetry.proto.resource.v1.Resource
	(*v1.InstrumentationScope)(nil), // 16: opentelemetry.proto.common.v1.InstrumentationScope
}
var file_opentelemetry_proto_profiles_v1development_profiles_proto_depIdxs = []int32{
	10, // 0: opentelemetry.proto.profiles.v1development.ProfilesDictionary.mapping_table:type_name -> opentelemetry.proto.profiles.v1development.Mapping
	11, // 1: opentelemetry.proto.profiles.v1development.ProfilesDictionary.location_table:type_name -> opentelemetry.proto.profiles.v1development.Location
	13, // 2: opentelemetry.proto.profiles.v1development.ProfilesDictionary.function_table:type_name -> opentelemetry.proto.profiles.v1development.Function
	7,  // 3: opentelemetry.proto.profiles.v1development.ProfilesDictionary.link_table:type_name -> opentelemetry.proto.profiles.v1development.Link
	14, // 4: opentelemetry.proto.profiles.v1development.ProfilesDictionary.attribute_table:type_name -> opentelemetry.proto.common.v1.KeyValue
	6,  // 5: opentelemetry.proto.profiles.v1development.ProfilesDictionary.attribute_units:type_name -> opentelemetry.proto.profiles.v1development.AttributeUnit
	3,  // 6: opentelemetry.proto.profiles.v1development.ProfilesData.resource_profiles:type_name -> opentelemetry.proto.profiles.v1development.ResourceProfiles
	1,  // 7: opentelemetry.proto.profiles.v1development.ProfilesData.dictionary:type_name -> opentelemetry.proto.profiles.v1development.ProfilesDictionary
	15, // 8: opentelemetry.proto.profiles.v1development.ResourceProfiles.resource:type_name -> opentelemetry.proto.resource.v1.Resource
	4,  // 9: opentelemetry.proto.profiles.v1development.ResourceProfiles.scope_profiles:type_name -> opentelemetry.proto.profiles.v1development.ScopeProfiles
	16, // 10: opentelemetry.proto.profiles.v1development.ScopeProfiles.scope:type_name -> opentelemetry.proto.common.v1.InstrumentationScope
	5,  // 11: opentelemetry.proto.profiles.v1development.ScopeProfiles.profiles:type_name -> opentelemetry.proto.profiles.v1development.Profile
	8,  // 12: opentelemetry.proto.profiles.v1development.Profile.sample_type:type_name -> opentelemetry.proto.profiles.v1development.ValueType
	9,  // 13: opentelemetry.proto.profiles.v1development.Profile.sample:type_name -> opentelemetry.proto.profiles.v1development.Sample
	8,  // 14: opentelemetry.proto.profiles.v1development.Profile.period_type:type_name -> opentelemetry.proto.profiles.v1development.ValueType
	0,  // 15: opentelemetry.proto.profiles.v1development.ValueType.aggregation_temporality:type_name -> opentelemetry.proto.profiles.v1development.AggregationTemporality
	12, // 16: opentelemetry.proto.profiles.v1development.Location.line:type_name -> opentelemetry.proto.profiles.v1development.Line
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_opentelemetry_proto_profiles_v1development_profiles_proto_init() }
func file_opentelemetry_proto_profiles_v1development_profiles_proto_init() {
	if File_opentelemetry_proto_profiles_v1development_profiles_proto != nil {
		return
	}
	file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[8].OneofWrappers = []any{}
	file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes[10].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_opentelemetry_proto_profiles_v1development_profiles_proto_rawDesc), len(file_opentelemetry_proto_profiles_v1development_profiles_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_opentelemetry_proto_profiles_v1development_profiles_proto_goTypes,
		DependencyIndexes: file_opentelemetry_proto_profiles_v1development_profiles_proto_depIdxs,
		EnumInfos:         file_opentelemetry_proto_profiles_v1development_profiles_proto_enumTypes,
		MessageInfos:      file_opentelemetry_proto_profiles_v1development_profiles_proto_msgTypes,
	}.Build()
	File_opentelemetry_proto_profiles_v1development_profiles_proto = out.File
	file_opentelemetry_proto_profiles_v1development_profiles_proto_goTypes = nil
	file_opentelemetry_proto_profiles_v1development_profiles_proto_depIdxs = nil
}
