# This action adds the latest milestone to a pull request
# when it is merged

name: 'Project: Add PR to Milestone'
on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const milestones = github.rest.issues.listMilestones({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: "open"
            })
            console.log(milestones)
            for (const milestone of milestones) {
              console.log(milestone)
              if (milestone.title.startsWith("v")) {
                console.log("found it")
                //await github.issues.update({
                  //owner: context.repo.owner,
                  //repo: context.repo.repo,
                  //issue_number: ${{ github.event.pull_request.number }},
                  //milestone: milestone.number
                //});
                //return
              }
            }
