name: prepare-release

on:
  workflow_dispatch:
    inputs:
      candidate-stable:
        required: true
        description: Release candidate version (stable)
      current-stable:
        required: true
        description: Current version (stable)
      candidate-beta:
        required: true
        description: Release candidate version (stable)
      current-beta:
        required: true
        description: Current version (stable)

jobs:
  prepare-release:
    runs-on: ubuntu-latest
    steps:
      - name: Check blockers in core
        run: |
          blockers=$( gh issue list --search "label:bug" --json url --jq '.[].title' )
          if [ "${blockers}" != "" ]; then
              echo "Release blockers in opentelemetry-collector repo: ${blockers}"
              exit 1
          fi
      - name: Check blockers in contrib
        run: |
          blockers=$( gh issue list --search "label:bug" --json url --jq '.[].title' --repo open-telemetry/opentelemetry-collector-contrib )
          if [ "${blockers}" != "" ]; then
              echo "Release blockers in opentelemetry-collector-contrib repo: ${blockers}"
              exit 1
          fi
