name: Automation - Release

on:
  workflow_dispatch:
    inputs:
      candidate-stable:
        required: true
        description: Release candidate version (stable, like 1.0.0-rc4)

      candidate-beta:
        required: true
        description: Release candidate version (beta, like 0.70.0)

      git-commit:
        require: true
        description: Changelog update commit (like 2b9639707)

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      # Create a branch named `release/<release-series>` (e.g. `release/v0.45.x`) from the changelog update commit and push to `open-telemetry/opentelemetry-collector`.
      - name: Push release branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: open-telemetry/opentelemetry-collector
          COMMIT: "${{ inputs.git-commit }}"
          CANDIDATE_STABLE: "${{ inputs.candidate-stable }}"
          CANDIDATE_BETA: "${{ inputs.candidate-beta }}"
        run: ./.github/workflows/scripts/release-create-branch.sh
      # Tag all the module groups (stable, beta) with the new release version by running the `make push-tags`
      # command (e.g. `make push-tags MODSET=stable` and `make push-tags MODSET=beta`). Wait for the new tag build to pass successfully.
      - name: Push tags for beta modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODSET: beta
        run: ./.github/workflows/scripts/release-push-tags.sh
      - name: Push tags for stable modules
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODSET: stable
        run: ./.github/workflows/scripts/release-push-tags.sh
