name: Automation - Renovate

on:
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.4.0
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v36.0.1
        with:
          renovate-version: 35.0.0
          configurationFile: .github/renovate-config.js
          token: ${{ secrets.CODEBOTEN_COLLECTOR_TOKEN }}
